import { Language } from './types';

export const UI_TEXT: Record<Language, Record<string, string>> = {
  en: {
    appName: 'ReliefQR',
    tagline: 'Swift Aid, Simplified.',
    selectLanguage: 'Select Your Language',
    english: 'English',
    hindi: 'हिन्दी',
    chatWelcome: "Hello! I'm ReliefBot. I'm here to help. Please tell me what you need.",
    yourTurn: 'Your Turn...',
    send: 'Send',
    needWater: 'I need water',
    needFood: 'I need food',
    imInjured: "I'm injured",
    needShelter: 'I need shelter',
    uploadPhoto: 'Upload Photo of Injury/Scene',
    uploading: 'Uploading...',
    analyzing: 'Analyzing Image...',
    generatingQR: 'Generating QR Code...',
    summaryTitle: 'Information Summary',
    summaryIntro: 'Please review the information below. This will be encoded in your QR code.',
    name: 'Name',
    age: 'Age',
    location: 'Location',
    needs: 'Immediate Needs',
    injuryDetails: 'Injury Details',
    photoAnalysis: 'Photo Analysis',
    edit: 'Edit',
    confirm: 'Confirm & Generate QR',
    qrTitle: 'Your ReliefQR Code',
    qrInstruction: 'Show this QR code to a relief worker. They can scan it to get your information quickly.',
    printReport: 'Print Report',
    startOver: 'Start Over',
    error: 'An error occurred. Please try again.',
    imageError: 'Could not analyze the image. Please try again or describe the situation.',
    dashboardTitle: 'What do you need to do?',
    generateReport: 'Generate Relief QR',
    generateReportDesc: 'Answer questions to create a QR code with your information.',
    scanQR: 'Scan Information QR',
    scanQRDesc: "Scan a code to view someone's information and needs.",
    analyzeScene: 'Analyze Injury/Scene',
    analyzeSceneDesc: 'Use the camera for an instant analysis of an injury or a scene.',
    scanInstruction: 'Point your camera at a ReliefQR code to scan it.',
    captureAndDecode: 'Capture & Decode (Simulated)',
    scannedDataTitle: 'Scanned Information',
    noDataScanned: 'No data found in QR code.',
    backToDashboard: 'Back to Dashboard',
    analyzeImageTitle: 'Analyze Image',
    imageAnalysisResult: 'Image Analysis Result:',
    takePhoto: 'Take Photo',
    uploadImage: 'Upload Image',
    analysisComplete: 'Analysis Complete',
    roleSelectTitle: 'Are you a...',
    personInNeed: 'Person in Need',
    volunteer: 'Volunteer',
    volunteerChatWelcome: 'Hello! I am a support bot for relief volunteers. How can I assist you?',
    reportIncident: 'Report Incident',
    requestSupplies: 'Request Supplies',
    situationUpdate: 'Situation Update',
    volunteerName: 'Volunteer Name',
    issueType: 'Issue Type',
    details: 'Details',
    urgency: 'Urgency',
    emergencyContacts: 'Emergency Contacts',
    call: 'Call',
    nationalEmergency: 'National Emergency',
    findHospitals: 'Find Nearby Hospitals',
    findHospitalsDesc: 'Use your location to find the nearest medical facilities.',
    nearbyHospitals: 'Nearby Hospitals',
    directions: 'Directions',
    gettingLocation: 'Getting your location...',
    findingHospitals: 'Finding nearby hospitals...',
    locationError: 'Could not access your location. Please enable location services in your browser settings.',
    getHelp: 'Get Help',
    getHelpDesc: 'Get guided assistance for your situation.',
    helpChatWelcome: 'I am here to provide immediate guidance. Please describe your situation or upload a photo.',
    someoneBleeding: 'Someone is Bleeding',
    fireHazard: 'Fire Hazard',
    structuralDamage: 'Structural Damage',
    accessibility: 'Accessibility',
    textToSpeech: 'Text-to-Speech',
    speechToText: 'Speech-to-Text',
    emergencySOS: 'Emergency SOS',
    emergencyQuestion1: 'Are you in an emergency? Please say yes or no.',
    emergencyQuestion2: 'Should I dial emergency services? Please say yes or no.',
    listening: 'Listening...',
    callingForHelp: 'Calling for help...',
    emergencyCancelled: 'Emergency request cancelled.',
  },
  hi: {
    appName: 'रिलीफQR',
    tagline: 'त्वरित सहायता, सरलीकृत।',
    selectLanguage: 'अपनी भाषा चुनें',
    english: 'English',
    hindi: 'हिन्दी',
    chatWelcome: 'नमस्ते! मैं रिलीफबॉट हूँ। मैं यहाँ मदद के लिए हूँ। कृपया मुझे बताएं कि आपको क्या चाहिए।',
    yourTurn: 'आपकी बारी...',
    send: 'भेजें',
    needWater: 'मुझे पानी चाहिए',
    needFood: 'मुझे खाना चाहिए',
    imInjured: 'मैं घायल हूँ',
    needShelter: 'मुझे आश्रय चाहिए',
    uploadPhoto: 'चोट/दृश्य की तस्वीर अपलोड करें',
    uploading: 'अपलोड हो रहा है...',
    analyzing: 'छवि का विश्लेषण हो रहा है...',
    generatingQR: 'QR कोड बन रहा है...',
    summaryTitle: 'सूचना सारांश',
    summaryIntro: 'कृपया नीचे दी गई जानकारी की समीक्षा करें। यह आपके QR कोड में एन्कोड किया जाएगा।',
    name: 'नाम',
    age: 'उम्र',
    location: 'स्थान',
    needs: 'तत्काल आवश्यकताएं',
    injuryDetails: 'चोट का विवरण',
    photoAnalysis: 'फोटो विश्लेषण',
    edit: 'संपादित करें',
    confirm: 'पुष्टि करें और QR उत्पन्न करें',
    qrTitle: 'आपका रिलीफQR कोड',
    qrInstruction: 'यह QR कोड किसी राहत कार्यकर्ता को दिखाएं। वे आपकी जानकारी जल्दी से प्राप्त करने के लिए इसे स्कैन कर सकते हैं।',
    printReport: 'रिपोर्ट प्रिंट करें',
    startOver: 'फिर से शुरू करें',
    error: 'एक त्रुटि हुई। कृपया पुन: प्रयास करें।',
    imageError: 'छवि का विश्लेषण नहीं हो सका। कृपया पुनः प्रयास करें या स्थिति का वर्णन करें।',
    dashboardTitle: 'आपको क्या करने की आवश्यकता है?',
    generateReport: 'राहत QR जेनरेट करें',
    generateReportDesc: 'अपनी जानकारी के साथ एक QR कोड बनाने के लिए सवालों के जवाब दें।',
    scanQR: 'सूचना QR स्कैन करें',
    scanQRDesc: 'किसी की जानकारी और जरूरतों को देखने के लिए एक कोड स्कैन करें।',
    analyzeScene: 'चोट/दृश्य का विश्लेषण करें',
    analyzeSceneDesc: 'चोट या दृश्य का तत्काल विश्लेषण प्राप्त करने के लिए कैमरे का उपयोग करें।',
    scanInstruction: 'स्कैन करने के लिए अपने कैमरे को रिलीफक्यूआर कोड पर इंगित करें।',
    captureAndDecode: 'कैप्चर और डीकोड (सिम्युलेटेड)',
    scannedDataTitle: 'स्कैन की गई जानकारी',
    noDataScanned: 'QR कोड में कोई डेटा नहीं मिला।',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    analyzeImageTitle: 'छवि का विश्लेषण करें',
    imageAnalysisResult: 'छवि विश्लेषण परिणाम:',
    takePhoto: 'तस्वीर खींचो',
    uploadImage: 'छवि अपलोड करें',
    analysisComplete: 'विश्लेषण पूरा हुआ',
    roleSelectTitle: 'आप हैं...',
    personInNeed: 'ज़रूरतमंद व्यक्ति',
    volunteer: 'स्वयंसेवक',
    volunteerChatWelcome: 'नमस्ते! मैं राहत स्वयंसेवकों के लिए एक समर्थन बॉट हूँ। मैं आपकी कैसे सहायता कर सकता हूँ?',
    reportIncident: 'घटना की रिपोर्ट करें',
    requestSupplies: 'आपूर्ति का अनुरोध करें',
    situationUpdate: 'स्थिति अपडेट',
    volunteerName: 'स्वयंसेवक का नाम',
    issueType: 'समस्या का प्रकार',
    details: 'विवरण',
    urgency: 'अत्यावश्यकता',
    emergencyContacts: 'आपातकालीन संपर्क',
    call: 'कॉल करें',
    nationalEmergency: 'राष्ट्रीय आपातकाल',
    findHospitals: 'आस-पास के अस्पताल खोजें',
    findHospitalsDesc: 'निकटतम चिकित्सा सुविधाओं को खोजने के लिए अपने स्थान का उपयोग करें।',
    nearbyHospitals: 'आस-पास के अस्पताल',
    directions: 'दिशा-निर्देश',
    gettingLocation: 'आपका स्थान प्राप्त किया जा रहा है...',
    findingHospitals: 'आस-पास के अस्पताल खोजे जा रहे हैं...',
    locationError: 'आपके स्थान तक नहीं पहुंच सका। कृपया अपनी ब्राउज़र सेटिंग्स में स्थान सेवाएं सक्षम करें।',
    getHelp: 'सहायता प्राप्त करें',
    getHelpDesc: 'अपनी स्थिति के लिए निर्देशित सहायता प्राप्त करें।',
    helpChatWelcome: 'मैं तत्काल मार्गदर्शन प्रदान करने के लिए यहां हूं। कृपया अपनी स्थिति का वर्णन करें या एक फोटो अपलोड करें।',
    someoneBleeding: 'किसी को खून बह रहा है',
    fireHazard: 'आग का खतरा',
    structuralDamage: 'ढांचागत क्षति',
    accessibility: 'सरल उपयोग',
    textToSpeech: 'टेक्स्ट-टू-स्पीच',
    speechToText: 'स्पीच-टू-टेक्स्ट',
    emergencySOS: 'आपातकालीन एसओएस',
    emergencyQuestion1: 'क्या आप आपात स्थिति में हैं? कृपया हाँ या नहीं कहें।',
    emergencyQuestion2: 'क्या मुझे आपातकालीन सेवाओं को डायल करना चाहिए? कृपया हाँ या नहीं कहें।',
    listening: 'सुन रहा है...',
    callingForHelp: 'मदद के लिए कॉल किया जा रहा है...',
    emergencyCancelled: 'आपातकालीन अनुरोध रद्द कर दिया गया।',
  },
};

export const EMERGENCY_CONTACTS = [
  { nameKey: 'nationalEmergency', number: '112' },
];